name: image_picker_example
description: Demonstrates how to use the image_picker plugin.
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.19.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_plugin_android_lifecycle: 
     git: https://github.com/kumsumit/flutter_plugin_android_lifecycle.git
  image_picker_android:
    # When depending on this package from a real application you should use:
    #   image_picker_android: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  image_picker_platform_interface: 
    git: https://github.com/kumsumit/image_picker_platform_interface.git
  mime: ^1.0.4
  video_player: 
     git: https://github.com/kumsumit/video_player.git

dev_dependencies:
  build_runner: ^2.1.10
  espresso: ^0.2.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
