name: image_picker_android
publish_to: none
description: Android implementation of the image_picker plugin.
repository: https://github.com/flutter/packages/tree/main/packages/image_picker/image_picker_android
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+image_picker%22
version: 0.8.12+13

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

flutter:
  plugin:
    implements: image_picker
    platforms:
      android:
        package: io.flutter.plugins.imagepicker
        pluginClass: ImagePickerPlugin
        dartPluginClass: ImagePickerAndroid

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: 
    git: https://github.com/kumsumit/flutter_plugin_android_lifecycle.git
  image_picker_platform_interface: 
    git: https://github.com/kumsumit/image_picker_platform_interface.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  pigeon: 
    git: https://github.com/kumsumit/pigeon.git

topics:
  - camera
  - image-picker
  - files
  - file-selection
